version: '3.8'

services:
  postgres:
    container_name: postgres
    # image: mariagornashevich/postgres:15
    build: 
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - home-library
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    networks:
      - home-library
    restart: always
    volumes:
      - /app/node_modules
      - ./src:/app/src


networks:
  home-library:
    driver: bridge

volumes:
  postgres_data:
    name: postgres-data